### ISSUE TITLE
Add Dating Sim

### ISSUE THREAD

**Issue by FudgeMobile** [unseeyou/unseebot#15]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by unseeyou** [comment]
ok

**Comment by FudgeMobile** [comment]
Add a dating sim

**Comment by unseeyou** [comment]
will be added soon

;P

**Comment by unseeyou** [comment]
sike you thought
